name: Build and Deploy

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    name: SlideRule Build and Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout SlideRule Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::742127912612:role/GitHubAction-AssumeRoleWithAction
        aws-region: us-east-1

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v3    

    - name: Upload Terraform
      run: |
       cd targets/slideruleearth-aws
       make cluster-upload-terraform

    - name: Build Containers
      run: |
       cd targets/slideruleearth-aws
       make BUILDX=buildx DOCKER_PLATFORM="--platform linux/arm64" cluster-docker

    - name: Push containers
      run: |
       cd targets/slideruleearth-aws
       make cluster-docker-push

#    - name: Build AMI
#      run: |
#       cd targets/slidruleearth-aws
#       make cluster-build-packer
