# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "SelfTest"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 5' # Every Sunday at 10 pm

  
jobs:
  self_test:
    name: Sliderule regression test
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install build-essential libreadline-dev liblua5.3-dev

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build sliderule
      run: |
       make config
       make
       sudo make install
    
    - name: Run regression (self) test
      run: sliderule ./scripts/selftests/test_runner.lua
